#!/bin/bash
echo "Best School" > '\*\\'"Best School"\'\\*$\?\*\*\*\*:)[D[D\*[B:)[D[C[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D'\' "Best School"\'\''\\*$\?\*\[C\*\*\*:)'
