#!/bin/bash
echo "$USER"[D[D[D[D[D[DHello $USER"[D[D[D[D[D[D[D[D[D[D[h[C[C[C[C[C[C[C"hello $USER[D[D[D[D[D[D[D[D[D[D[D[D[C[C[C[C[C[C[C[echo "hello $USER"
