#!/bin/bash
echo $PATH | tr ':' '\n' |wc -l
[C[C[C[C[C[6~[6~[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C wc -l[B[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D