#!/bin/bash
export BEST="School"
[C[C[C[C[C[C[C[C[C[C[C[C[C[A[D[B[D[D[D[A[D[D[D[D[D[D[D[D[D[B[A[C[C[C[C[C[C[C[C[C[C[C[C[C[S[D[D[D[D[D[A[B[B[D[D[D[D[D[D[D[D[D